name: SmallRye Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build using Maven

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: AdoptOpenJDK/install-jdk@v1
        name: Set up JDK 12
        with:
          version: 12

      - uses: AdoptOpenJDK/install-jdk@v1
        name: Set up JDK 8
        with:
          version: 8
          targets: 'JAVA_HOME_8'

      - name: Build
        run: mvn -B formatter:validate verify --file pom.xml -Djava8.home=$JAVA_HOME_8 javadoc:javadoc

  quality:
    needs: [build]
    if: github.event_name == 'push' && startsWith('smallrye', github.repository)
    runs-on: ubuntu-latest
    name: quality

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 8

      - name: sonar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -B verify --file pom.xml -Pcoverage javadoc:javadoc sonar:sonar -Dsonar.projectKey=smallrye_smallrye-safer-annotations -Dsonar.login=$SONAR_TOKEN
